spring:
  datasource:
    driver: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/vipaccount?serverTimezone=GMT&allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=utf8
    username: root
    password: suhaipeng123

    servlet:
      multipart:
        enabled: true
        #      最大支持文件大小
        max-file-size: 100MB
        #      最大支持请求大小
        max-request-size: 100MB

mybatis:
  configuration:
    map-underscore-to-camel-case: true

